# Generated by Django 5.0.3 on 2024-04-26 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='主菜', to='recipes.recipe')),
                ('side_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='副菜', to='recipes.recipe')),
                ('soup_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='汁物', to='recipes.recipe')),
                ('staple_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='主食', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
