# Generated by Django 5.0.3 on 2024-05-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_userevaluation_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='is_next_3_day_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='is_next_day_excluded',
            field=models.BooleanField(default=False),
        ),
    ]
