# Generated by Django 5.0.3 on 2024-04-19 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_users_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='adult_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='users',
            name='children_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='cooking_time_min',
            field=models.IntegerField(choices=[(10, '10分以内'), (20, '20分以内'), (30, '30分以内')], null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='users',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
