# Generated by Django 5.0.3 on 2024-06-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_users_cooking_time_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cooking_time_min',
            field=models.IntegerField(choices=[(None, '選択してください'), (10, '10分以内'), (20, '20分以内'), (30, '30分以内')], default=30),
        ),
    ]
